### ISSUE TITLE
Cannot start a dev version

### ISSUE THREAD

**Issue by RafikiTiki** [RebelliousToken/RebelliousWallet#2]
Hi guys i wanted to tweak height of your app because I'm using a 1366x768 laptop and your app i set to be 768px vertical and don't allow user resizing. I'm using ubuntu so fixed app height of 768px plus heights of  app window top bar and system menu is causing bottom buttons in app hidden 'below' screen making them unaccessible.

I wanted to make quick fix to make app resizible (in sane way - setting max and min dimensions) but i can't start dev version of the app because there's no config.js file in repo and no information about this file in readme either. If you guys can tell me what should be in `config.js` I'll be happy to make PR with these resize changes because now the only way to make wallet usable is to connect laptop to external display with higher resolution.

Error after starting dev version of wallet app: 
```
Uncaught Exception:
Error: Cannot find module './config'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/rafal/Documents/RebelliousWallet/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/rafal/Documents/RebelliousWallet/src/main.js:13:16)
    at Object.<anonymous> (/home/rafal/Documents/RebelliousWallet/src/main.js:91:3)
    at Module._compile (module.js:571:32)
    at Object.require.extensions.(anonymous function) [as .js] (/home/rafal/Documents/RebelliousWallet/node_modules/electron-compile/lib/require-hook.js:77:14)
    at Module.load (module.js:488:32)
```

**Comment by RebelliousToken** [comment]
Hi RafikiTiki,

Copy /src/config.prod.js to /src/config.js:
`cp src/config.prod.js src/config.js`
and then start app once again:
`npm start`

Best regards,
Rebellious team
