### ISSUE TITLE
web3 is not defined

### ISSUE THREAD

**Issue by oritwoen** [RebelliousToken/RebelliousWallet#5]
When running the new version 0.3. Version 0.2 worked normally.

```
[17:16:34.997] [error] ReferenceError: web3 is not defined
    at OpenPrivateKey (file:///home/inder/.app/.source/.rebellious/dist/linux-unpacked/resources/app.asar/src/js/main.js:332:7)
    at HTMLButtonElement.onclick (file:///home/inder/.app/.source/.rebellious/dist/linux-unpacked/resources/app.asar/src/index.html:239:88) OpenPrivateKey
[17:16:47.473] [error] ReferenceError: web3 is not defined
    at OpenPrivateKey (file:///home/inder/.app/.source/.rebellious/dist/linux-unpacked/resources/app.asar/src/js/main.js:332:7)
    at HTMLButtonElement.onclick (file:///home/inder/.app/.source/.rebellious/dist/linux-unpacked/resources/app.asar/src/index.html:239:88) OpenPrivateKey
```

**Comment by RebelliousToken** [comment]
Hello @redni,

We suggest to update Node.js from npm. For Rebellious Wallet minimum recommend version node js - 9.4.0.

Best regards,
Rebellious Team
